version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build-and-test:
    docker:
      - image: hashicorp/jsii-terraform:0.12.24
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install -g cdktf-cli
            - run: npm install
            - run: cdktf get
            - run: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test
